create table if not exists MEMBERS (
	MKEY VARCHAR2 NOT NULL,
	NAME VARCHAR2 NOT NULL,
	EMAIL VARCHAR2 NOT NULL,
	PRIMARY KEY (MKEY)
);

create table if not exists TEAMS (
	TKEY VARCHAR2 IDENTITY,
	TITLE VARCHAR2 NOT NULL,
	DESCRIPTION VARCHAR2 NOT NULL,
	PRIMARY KEY (TKEY)
);

create table if not exists TEAM_MEMBERS (
	TEAM_KEY VARCHAR2 NOT NULL,
	MEMBER_KEY VARCHAR2 NOT NULL,
	RATING NUMBER DEFAULT 100,
	PRIMARY KEY(TEAM_KEY, MEMBER_KEY)
);